export const LocationsList = [
  {
    FirstName: "דני",
    LastName: "רביד",
    Address: "האלמוגים 24",
    AvgDonations: 100,
    Floor: 0,
    Apartment: 1,
    Remark: "שער סגור לבוא מסביב",
  },
  {
    FirstName: "איתי",
    LastName: "לוי",
    Address: "רוטשילד 10",
    AvgDonations: 600,
    Floor: 2,
    Apartment: 4,
    Remark: "בינה 4, דלת אחורית",
  },
  {
    FirstName: "שירה",
    LastName: "כהן",
    Address: "הנביאים 5",
    AvgDonations: 200,
    Floor: 3,
    Apartment: 12,
    Remark: "קוד לדלת 1234",
  },
  {
    FirstName: "יוסי",
    LastName: "מזרחי",
    Address: "בן גוריון 7",
    AvgDonations: 60,
    Floor: 1,
    Apartment: 4,
    Remark: "להשאיר מתחת לשטיח",
  },
  {
    FirstName: "תמר",
    LastName: "גולן",
    Address: "הברזל 34",
    AvgDonations: 53,
    Floor: 4,
    Apartment: 19,
    Remark: "לצלצל פעמיים",
  },
];
